## Numpy Exercise

## Create an array of 10 zeros and change the fifth value to 1.

In [ ]:
import numpy as np
array1=np.zeros(10)

In [3]:
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
array1[9]=1

In [5]:
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

## Create a NumPy array with values from 10 to 50.

In [6]:
array2=np.arange(10,50)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Create an array of even numbers from 2 to 20.



In [8]:
array_even=np.arange(2,21,2)
array_even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Create a 3×3 matrix with values ranging from 0 to 8.

In [12]:
array4=np.arange(9).reshape(3,3)
array4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Find the shape, size, and data type of an array.

In [13]:
array4.shape

(3, 3)

In [14]:
array4.size

9

In [15]:
type(array4)

numpy.ndarray

## Create a 5×5 matrix with all values equal to 7.



In [17]:
array5=np.full((5,5),7)
array5

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

## Create a 1D array of 50 random integers between 1 and 100.

In [20]:
array_random=np.random.randint(1,100,size=50)
array_random

array([49, 44,  9, 52, 26, 77, 74,  6, 54, 81, 58, 51, 67, 22, 44, 26, 36,
       48, 51, 73, 34, 90, 73, 95, 74, 32, 21,  6, 67, 34, 93,  2, 23, 61,
       18, 30, 76, 73, 92, 21, 71, 91, 81, 42, 89, 45, 89, 92, 91, 87],
      dtype=int32)

## Reshape a 1D array of 12 elements into a 3×4 matrix.



In [24]:
array_new=np.arange(1,13)

In [25]:
array_new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
array_new.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Find the maximum, minimum, and mean of a NumPy array.

In [27]:
array_new.min()

np.int64(1)

In [28]:
array_new.max()

np.int64(12)

In [29]:
array_new.mean()

np.float64(6.5)

In [30]:
array_new.sum()

np.int64(78)

## Reverse a NumPy array (e.g., [1, 2, 3] → [3, 2, 1])

In [33]:
new_array_reverse=array_new[::-1]

In [34]:
new_array_reverse

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Find the index of the maximum and minimum values in a NumPy array.

In [36]:
max_index=new_array_reverse.argmax()
max_index

np.int64(0)

In [37]:
min_index=new_array_reverse.argmin()
min_index

np.int64(11)

## Create a 4×4 identity matrix

In [38]:
identity_matrix=np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##  Replace all odd numbers in an array with -1



In [42]:
array6=np.arange(10)
array6[array6 %2!=0]=-1
array6

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. Extract all even numbers from a 2D array


In [43]:
array_2D=np.array([[1,2,3],[4,5,6]])
even_value=array_2D[array_2D %2==0]
even_value

array([2, 4, 6])