## Numpy Implementation

In [4]:
import numpy as np

arr1=np.array([10,20,30])
arr1


array([10, 20, 30])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(3,)

In [7]:
arr2=np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

In [8]:
arr2.shape

(2, 3)

In [9]:
type(arr2)

numpy.ndarray

In [10]:
arr3=np.array([[[1,2,3],[4,5,6],[8,9,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [8, 9, 6]]])

In [11]:
arr3.shape

(1, 3, 3)

In [12]:
type(arr3)

numpy.ndarray

In [13]:
arr1[0]

np.int64(10)

In [14]:
arr1[1]

np.int64(20)

In [16]:
arr2[0][0]

np.int64(1)

## Zeros and Ones

In [17]:
np.zeros((1,2))

array([[0., 0.]])

In [18]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [22]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
array1=np.arange(25,100,2)
array1

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91,
       93, 95, 97, 99])

In [27]:
np.sum(array1)

np.int64(2356)

In [28]:
np.mean(array1)

np.float64(62.0)

In [29]:
np.max(array1)

np.int64(99)

In [30]:
np.min(array1)

np.int64(25)

In [31]:
new_arry=[]

for i in array1:
    new_arry.append(i*3)
    

In [32]:
new_arry

[np.int64(75),
 np.int64(81),
 np.int64(87),
 np.int64(93),
 np.int64(99),
 np.int64(105),
 np.int64(111),
 np.int64(117),
 np.int64(123),
 np.int64(129),
 np.int64(135),
 np.int64(141),
 np.int64(147),
 np.int64(153),
 np.int64(159),
 np.int64(165),
 np.int64(171),
 np.int64(177),
 np.int64(183),
 np.int64(189),
 np.int64(195),
 np.int64(201),
 np.int64(207),
 np.int64(213),
 np.int64(219),
 np.int64(225),
 np.int64(231),
 np.int64(237),
 np.int64(243),
 np.int64(249),
 np.int64(255),
 np.int64(261),
 np.int64(267),
 np.int64(273),
 np.int64(279),
 np.int64(285),
 np.int64(291),
 np.int64(297)]

In [33]:
np.argmax(array1)

np.int64(37)

In [34]:
np.argmin(array1)

np.int64(0)

In [40]:
np.random.randint(1,10,2)

array([9, 3], dtype=int32)

In [41]:
np.random.random(size=10)

array([0.19031885, 0.12897209, 0.93325917, 0.66569999, 0.45729069,
       0.51195296, 0.40335945, 0.50472978, 0.52125599, 0.17975671])