## Numpy Implementation

In [4]:
import numpy as np

arr1=np.array([10,20,30])
arr1


array([10, 20, 30])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(3,)

In [7]:
arr2=np.array([[1,2,3],[5,6,7]])
arr2

array([[1, 2, 3],
       [5, 6, 7]])

In [8]:
arr2.shape

(2, 3)

In [9]:
type(arr2)

numpy.ndarray

In [10]:
arr3=np.array([[[1,2,3],[4,5,6],[8,9,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [8, 9, 6]]])

In [11]:
arr3.shape

(1, 3, 3)

In [12]:
type(arr3)

numpy.ndarray

In [13]:
arr1[0]

np.int64(10)

In [14]:
arr1[1]

np.int64(20)

In [16]:
arr2[0][0]

np.int64(1)